package com.gayathri.projects.service;

import com.gayathri.projects.dto.ShortnerRequestDTO;
import com.gayathri.projects.dto.ShortnerResponseDTO;
import com.gayathri.projects.exception.URLNotFoundException;
import com.gayathri.projects.model.URLShortner;
import com.gayathri.projects.repository.URLShortnerRepo;
import com.gayathri.projects.util.URLGenerator;
import com.gayathri.projects.exception.URLNotFoundException;
import com.gayathri.projects.exception.ErrorMessages;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/* A class always implements an interface*/
@Service
public class URLShortnerServiceImpl implements URLShortnerService
{
    @Autowired
    private URLShortnerRepo urlShortnerRepo;

    @Autowired
    private URLGenerator urlGenerator;

    /* 1. Override annotation tell spring that this method is meant to override a method from its super class or interface
    method overriding means implementation is different while method signature is same , we can only override a method from its parent's class
    overriding exhibits runtime polymorphism which means method gets executed by the its object type and not reference type

    * */
    @Override
    @CachePut(value = "urls", key = "#result.shortUrl")

    public ShortnerResponseDTO URLShortner(ShortnerRequestDTO shortnerrequestdto) {
        /* URLShortner.builder() lets us sets builder object when we annotated URLShortner with @builder, it sets fields one by one
        shortnerrequestdto.getOriginalurl() is generated by @Getter/@Data
        .build means it is telling spring that we set our required fields
         */
       URLShortner urlShortner = URLShortner.builder().longurl(shortnerrequestdto.getOriginalurl()).build();
       urlShortnerRepo.save(urlShortner);
       String shorturl= urlGenerator.shorten();
       urlShortner.setShorturl(shorturl);
       // adding a check to avoid giving duplicate shorten urls for two or more long urls
       while(urlShortnerRepo.existsByShorturl(shorturl))
       {
       shorturl= urlGenerator.shorten();
       }
       //Setting and saving unique short url
       urlShortner.setShorturl(shorturl);
       urlShortnerRepo.save(urlShortner);
       //return all details
        return ShortnerResponseDTO.builder().id(urlShortner.getId()).
                shortUrl(urlShortner.getShorturl()).originalUrl(urlShortner.getLongurl()).
                createdAt(urlShortner.getCreatedAt()).updatedAt(urlShortner.getUpdatedAt()).
                build();
    }

    /* We use @Cacheable annottaion so that it tells spring that the result of the method call should be cached
     * @Override This method is meant to override a method from a superclass or an interface.
     */
    @Override
    @Cacheable(value="urlcache",key="#shorturl")
    public String getOriginalURL(String shortUrl) {
        //Making sure that the generated shorturl is not null
        if(shortUrl == null || shortUrl.isEmpty()) {
            throw new IllegalArgumentException("Short URL cannot be null or empty");
        }
        URLShortner urlShortner = urlShortnerRepo.findByShorturl(shortUrl);
        //If generted shorturl is null, it throws an error
        if (urlShortner == null) {
            throw new URLNotFoundException(ErrorMessages.URL_NOT_FOUND);
        }
        //shorturl is saved and returned
        urlShortnerRepo.save(urlShortner);
        return urlShortner.getLongurl();

    }
}