package com.gayathri.projects.service;

import com.gayathri.projects.dto.ShortnerRequestDTO;
import com.gayathri.projects.dto.ShortnerResponseDTO;
import com.gayathri.projects.exception.URLNotFoundException;
import com.gayathri.projects.model.URLShortner;
import com.gayathri.projects.repository.URLShortnerRepo;
import com.gayathri.projects.util.URLGenerator;
import com.gayathri.projects.exception.ErrorMessages;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

/* A class always implements an interface*/

@Service
public class URLShortnerServiceImpl implements URLShortnerService
{
    @Autowired
    private URLShortnerRepo urlShortnerRepo;

    @Autowired
    private URLGenerator urlGenerator;

    /* 1. Override annotation tell spring that this method is meant to override a method from its super class or interface
    method overriding means implementation is different while method signature is same , we can only override a method from its parent's class
    overriding exhibits runtime polymorphism which means method gets executed by the its object type and not reference type

    * */
    @Override
    @CachePut(value="urlcache", key="#result.shortUrl")

    public ShortnerResponseDTO URLShortner(ShortnerRequestDTO shortnerrequestdto) {
        /* URLShortner.builder() lets us sets builder object when we annotated URLShortner with @builder, it sets fields one by one
        shortnerrequestdto.getOriginalurl() is generated by @Getter/@Data
        .build means it is telling spring that we set our required fields
         */

        if (shortnerrequestdto == null ||
                shortnerrequestdto.getOriginalurl() == null ||
                shortnerrequestdto.getOriginalurl().isBlank()) {
            throw new IllegalArgumentException("Original URL cannot be null or empty");
        }

        String shorturl = urlGenerator.shorten(shortnerrequestdto.getOriginalurl());

        // To check if the shorturl exists or not
        URLShortner existing = urlShortnerRepo.findByShorturl(shorturl);

        // if the url exists then return existing short url
        if (existing != null) {
            return ShortnerResponseDTO.builder()
                    .id(existing.getId())
                    .shortUrl(existing.getShorturl())
                    .originalUrl(existing.getLongurl())
                    .createdAt(existing.getCreatedAt())
                    .updatedAt(existing.getUpdatedAt())
                    .build();
        }

       //Setting and saving unique short url
        URLShortner urlShortner = URLShortner.builder()
                .longurl(shortnerrequestdto.getOriginalurl())
                .shorturl(shorturl)
                .build();
       urlShortnerRepo.save(urlShortner);
       //return all details
        return ShortnerResponseDTO.builder().id(urlShortner.getId()).
                shortUrl(urlShortner.getShorturl()).originalUrl(urlShortner.getLongurl()).
                createdAt(urlShortner.getCreatedAt()).updatedAt(urlShortner.getUpdatedAt()).
                build();
    }

    /* We use @Cacheable annottaion so that it tells spring that the result of the method call should be cached
     * @Override This method is meant to override a method from a superclass or an interface.
     */
    @Override
    @CachePut(value="urlcache",key="#shortUrl")
    public String getOriginalURL(String shortUrl) {
        //Making sure that the generated shorturl is not null
        if(shortUrl == null || shortUrl.isEmpty()) {
            throw new IllegalArgumentException("Short URL cannot be null or empty");
        }
        URLShortner urlShortner = urlShortnerRepo.findByShorturl(shortUrl);
        //If generted shorturl is null, it throws an error
        if (urlShortner == null) {
            throw new URLNotFoundException(ErrorMessages.URL_NOT_FOUND);
        }
        //shorturl is saved and returned
        urlShortnerRepo.save(urlShortner);
        return urlShortner.getLongurl();

    }
}