apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortify
  template:
    metadata:
      labels:
        app: shortify
    spec:
      containers:
        - name: shortify
          image: shortify-app:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shortify
spec:
  type: NodePort
  selector:
    app: shortify
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
